# Generated by Django 3.1 on 2020-08-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=30)),
                ('task_details', models.CharField(max_length=100)),
                ('task_status', models.CharField(choices=[('todo', 'TO-DO'), ('in-progress', 'IN-PROGRESS'), ('done', 'DONE')], default='todo', max_length=50)),
                ('task_create', models.DateTimeField(auto_now_add=True)),
                ('task_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
